import type { Product, ProductId } from "../core/types";

export const products: Record<ProductId, Product> = {
  soda: {
    id: "soda",
    name: "Corner Soda",
    category: "drink",
    cost: 2,
    basePrice: 5,
    size: 1,
    demand: 1.05,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["commuter", "laundry", "night"],
    shelfLifeHours: 96,
    description: "Cheap fizz with broad appeal."
  },
  chips: {
    id: "chips",
    name: "Salt Stack Chips",
    category: "snack",
    cost: 1,
    basePrice: 4,
    size: 1,
    demand: 0.9,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["student", "laundry", "arcade"],
    shelfLifeHours: 168,
    description: "Low-cost filler stock."
  },
  energy: {
    id: "energy",
    name: "Turbo Cola",
    category: "drink",
    cost: 4,
    basePrice: 9,
    size: 1,
    demand: 1.2,
    heat: 0.2,
    legality: 0,
    customizable: true,
    demandTags: ["gym", "commuter", "night"],
    shelfLifeHours: 96,
    description: "High-margin late-day fuel."
  },
  water: {
    id: "water",
    name: "Blue Tap Water",
    category: "drink",
    cost: 1,
    basePrice: 3,
    size: 1,
    demand: 0.82,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["commuter", "gym", "office"],
    shelfLifeHours: 120,
    description: "Low-margin, steady demand, and useful in hot districts."
  },
  protein_bar: {
    id: "protein_bar",
    name: "Brickhouse Protein Bar",
    category: "snack",
    cost: 3,
    basePrice: 7,
    size: 1,
    demand: 1.02,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["gym", "student", "commuter"],
    shelfLifeHours: 144,
    description: "Reliable gym and campus stock with better margins than chips."
  },
  coffee_can: {
    id: "coffee_can",
    name: "Night Shift Coffee",
    category: "drink",
    cost: 3,
    basePrice: 7,
    size: 1,
    demand: 1.08,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["commuter", "office", "night"],
    shelfLifeHours: 96,
    description: "Morning and late-shift caffeine in a can."
  },
  instant_noodles: {
    id: "instant_noodles",
    name: "Boiler Cup Noodles",
    category: "meal",
    cost: 4,
    basePrice: 10,
    size: 2,
    demand: 0.98,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["student", "night", "utility"],
    shelfLifeHours: 72,
    description: "Bulky meal stock for campuses, night stops, and industrial breaks."
  },
  phone_charger: {
    id: "phone_charger",
    name: "Panic Charger",
    category: "utility",
    cost: 6,
    basePrice: 15,
    size: 1,
    demand: 0.72,
    heat: 0,
    legality: 0,
    customizable: false,
    demandTags: ["commuter", "office", "night"],
    description: "Slow seller, high margin, strongest near transit and nightlife."
  },
  umbrella: {
    id: "umbrella",
    name: "Rain Check Umbrella",
    category: "utility",
    cost: 5,
    basePrice: 13,
    size: 2,
    demand: 0.66,
    heat: 0,
    legality: 0,
    customizable: false,
    demandTags: ["commuter", "office"],
    description: "Weather-sensitive utility item with bursty demand."
  },
  hygiene_kit: {
    id: "hygiene_kit",
    name: "Clean Slate Kit",
    category: "utility",
    cost: 4,
    basePrice: 11,
    size: 1,
    demand: 0.74,
    heat: 0,
    legality: 0,
    customizable: true,
    demandTags: ["commuter", "utility", "night"],
    shelfLifeHours: 180,
    description: "Travel and late-night utility stock with modest reputation value."
  },
  luxury_snack: {
    id: "luxury_snack",
    name: "Velvet Crunch Bar",
    category: "snack",
    cost: 7,
    basePrice: 18,
    size: 1,
    demand: 0.86,
    heat: 0.15,
    legality: 0,
    customizable: true,
    demandTags: ["office", "night", "arcade"],
    shelfLifeHours: 120,
    description: "Overpriced polish for rich lobbies and customers with bad impulse control."
  },
  mystery_capsules: {
    id: "mystery_capsules",
    name: "Mystery Capsules",
    category: "fictional-grey",
    cost: 7,
    basePrice: 16,
    size: 1,
    demand: 1.35,
    heat: 1.4,
    legality: 1,
    customizable: true,
    demandTags: ["arcade", "night"],
    shelfLifeHours: 72,
    description: "A fictional grey-market novelty that draws attention."
  },
  mood_fizz: {
    id: "mood_fizz",
    name: "Mood Fizz",
    category: "fictional-grey",
    cost: 8,
    basePrice: 19,
    size: 1,
    demand: 1.28,
    heat: 1.1,
    legality: 1,
    customizable: true,
    demandTags: ["night", "student", "arcade"],
    shelfLifeHours: 72,
    description: "Fictional nightlife soda with loyal customers and louder rumors."
  },
  glitch_gum: {
    id: "glitch_gum",
    name: "Glitch Gum",
    category: "fictional-grey",
    cost: 6,
    basePrice: 15,
    size: 1,
    demand: 1.18,
    heat: 0.85,
    legality: 1,
    customizable: true,
    demandTags: ["arcade", "student", "night"],
    shelfLifeHours: 120,
    description: "Bright foil gum that sells best near arcades and campus shortcuts."
  },
  night_syrup: {
    id: "night_syrup",
    name: "Night Syrup",
    category: "fictional-contraband",
    cost: 11,
    basePrice: 28,
    size: 1,
    demand: 1.42,
    heat: 2.4,
    legality: 2,
    customizable: true,
    demandTags: ["night", "arcade"],
    shelfLifeHours: 48,
    description: "A fictional after-hours bottle. Big money, big attention."
  },
  focus_cubes: {
    id: "focus_cubes",
    name: "Focus Cubes",
    category: "fictional-contraband",
    cost: 10,
    basePrice: 25,
    size: 1,
    demand: 1.36,
    heat: 2,
    legality: 2,
    customizable: true,
    demandTags: ["student", "office", "night"],
    shelfLifeHours: 96,
    description: "Abstract high-risk study fuel with serious inspection pressure."
  }
};
